#!/bin/sh
# Lightbar — Mosquitto entrypoint
# Version: 2.0.0
#
# Builds the password and ACL files from environment variables (.env)
# on every start, so changing credentials is just `docker compose up -d`.
set -eu

DATA="${MOSQUITTO_DATA:-/mosquitto/data}"
CONF="${MOSQUITTO_CONF:-/lightbar/mosquitto.conf}"
PASSWD="$DATA/passwd"
ACL="$DATA/acl"
PREFIX="${MQTT_TOPIC_PREFIX:-lightbar}"

for var in MQTT_HA_USER MQTT_HA_PASSWORD MQTT_DEVICE_USER MQTT_DEVICE_PASSWORD; do
    eval "value=\${$var:-}"
    if [ -z "$value" ]; then
        echo "[lightbar] $var is empty — set it in .env" >&2
        exit 1
    fi
done
for pw in "$MQTT_HA_PASSWORD" "$MQTT_DEVICE_PASSWORD"; do
    case "$pw" in
        change-me*)
            echo "[lightbar] Refusing to start with a default password — edit .env" >&2
            exit 1 ;;
    esac
done
if [ "$MQTT_HA_USER" = "$MQTT_DEVICE_USER" ]; then
    echo "[lightbar] MQTT_HA_USER and MQTT_DEVICE_USER must be different" >&2
    exit 1
fi

umask 077
mkdir -p "$DATA"
rm -f "$PASSWD"
mosquitto_passwd -c -b "$PASSWD" "$MQTT_HA_USER" "$MQTT_HA_PASSWORD"
mosquitto_passwd -b "$PASSWD" "$MQTT_DEVICE_USER" "$MQTT_DEVICE_PASSWORD"

cat > "$ACL" <<ACL_EOF
# Generated by entrypoint.sh — edits are overwritten on restart.

# Home Assistant: everything (+ \$SYS, which "#" never matches; used by the healthcheck)
user $MQTT_HA_USER
topic readwrite #
topic read \$SYS/#

# Lightbar: its own topics, publish discovery, hear HA restarts
user $MQTT_DEVICE_USER
topic readwrite $PREFIX/#
topic write homeassistant/#
topic read homeassistant/status
ACL_EOF

if id mosquitto >/dev/null 2>&1; then
    chown -R mosquitto:mosquitto "$DATA"
fi
echo "[lightbar] Broker users: $MQTT_HA_USER (Home Assistant), $MQTT_DEVICE_USER (device)"
exec mosquitto -c "$CONF"
